FROM node:8-alpine

WORKDIR /usr/src

#nginx settings
COPY ./nginx.conf /etc/nginx/conf.d/web/

COPY ./yarn.lock /usr/src/
COPY ./package.json /usr/src/

RUN yarn install

COPY . /usr/src

VOLUME ["/var/www/web", "/etc/nginx/conf.d/web"]

CMD ["yarn", "run", "develop"]